Add `AnnotationForge` to `Suggests`
Solves the following `R CMD check` error:
```
 ERROR
Errors in running code in vignettes:
when running code in ‘GCSscore.Rnw’
  ...
*This package will only be generated once for each chip-type*
*Or if probeFile version for the chip-type needs to be updated*
writing intermediary .probe_tab file to temporary directory
Importing the data.
Warning in packageDescription(thispkg) :
  no package 'AnnotationForge' was found

  When sourcing ‘GCSscore.R’:
Error: $ operator is invalid for atomic vectors
Execution halted
```